---
title: "Grade Analysis"
author: Daniel Rohrbach
format: html
editor: visual
echo: false
message: false
warning: false
---

```{r}
here::i_am("r-101-grade-analysis.Rproj")
library(here)
library(ggplot2)
library(dplyr)
library(tidyr)
library(vroom)
```
## Question 1
```{r}
grades <- vroom(here("grades.csv"))
```
## Question 2
```{r}
exam_stats <- grades |> 
  summarise(
    Min = min(Exam, na.rm = TRUE),
    Max = max(Exam, na.rm = TRUE),
    Median = median(Exam, na.rm = TRUE),
    Mean = mean(Exam, na.rm = TRUE)
  )

knitr::kable(exam_stats, caption = "Exam Statistics", align = 'c')
```

## Question 3
```{r}
missing_exam <- grades |> 
  filter(is.na(Exam)) |> 
  count()
```
We observe that `r missing_exam` students did not take the final exam.

## Question 4
```{r}
grades |> 
  filter(!is.na(Exam)) |> 
  ggplot(aes(x = Exam)) + 
  geom_histogram(binwidth = 1, fill = "blue", color = "black", alpha = 0.6) +
  labs(title = "Distribution of Exam Grades", 
       x = "Grade", 
       y = "Number of Students") +
  theme_minimal()
```

For reasons of graphical representation, .5 grades were rounded to full grades using the "binwidth=1" command. 

## Question 5
```{r}
group_counts <- grades |> 
  group_by(Group) |> 
  summarise(Count = n())

knitr::kable(group_counts, caption = "Number of Students per Group", align = 'c')
```

## Question 6
```{r}
grades |>
  group_by(Group) |>
  summarise(count = n()) |>
  ggplot(aes(x = Group, y = count)) + 
  geom_bar(stat = "identity", fill = "lightblue", color = "white") + 
  labs(title = "Number of Students in Each Group", 
       x = "Group", 
       y = "Number of Students") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1))
```


